"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { ArrowLeft, CalendarDays, CheckCircle2, ChevronRight, Clock3, House, LogOut, MapPin, QrCode, Search, UserRound, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { activities, ageOf, children, createBooking, dateTime, eligible, type Booking, loadBookings, money, remaining, saveBookings, sessions } from "@/lib/playnest-demo";
import { endDemoSession, isDemoSignedIn } from "@/lib/demo-session";

const app = "/app";
const getActivity = (id?: string) => activities.find(x => x.id === id);
const getSession = (id?: string) => sessions.find(x => x.id === id);
const getChild = (id?: string) => children.find(x => x.id === id);
const Nav = ({ path }: { path: string }) => <nav className="app-nav" aria-label="Main navigation"><Link href={app} className="app-brand"><img src="/images/playnest/b91dc68775b2.png" alt=""/> <span>PlayNest<small>Play. Learn. Grow.</small></span></Link><div><Link className={path === app ? "active" : ""} href={app}><House size={17}/> Home</Link><Link className={path.includes("activities") ? "active" : ""} href={`${app}/activities`}><Search size={17}/> Activities</Link><Link className={path.includes("bookings") ? "active" : ""} href={`${app}/bookings`}><CalendarDays size={17}/> My bookings</Link><Link className={path.includes("profile") ? "active" : ""} href={`${app}/profile`}><UserRound size={17}/> Profile</Link></div><button className="logout-button" aria-label="Log out of PlayNest" onClick={() => { endDemoSession(); window.location.assign("/login"); }}><LogOut size={17}/><span>Log out</span></button></nav>;
const Layout = ({ children: content, path }: { children: React.ReactNode; path: string }) => <><Nav path={path}/><main className="booking-main">{content}</main></>;
const Action = ({ href, children, muted = false }: { href: string; children: React.ReactNode; muted?: boolean }) => <Link href={href} className={`action ${muted ? "secondary" : ""}`}>{children}<ChevronRight size={17}/></Link>;
function ActivityCard({ activity, bookings }: { activity: typeof activities[number]; bookings: Booking[] }) { const open = sessions.filter(s => s.activityId === activity.id && s.status === "scheduled" && remaining(s, bookings) > 0).length; return <article className="activity-card"><img src={activity.image} alt={`${activity.name} activity in progress`}/><div className="activity-body"><span className="tag">Ages {activity.ages[0]}–{activity.ages[1]}</span><h2>{activity.name}</h2><p>{activity.description}</p><div className="meta"><span><Clock3 size={15}/>{activity.minutes} min</span><b>{money(activity.price)}</b></div><Link href={`${app}/activities/${activity.id}`} className="text-link">{open ? `${open} session${open === 1 ? "" : "s"} available` : "View sessions"}<ChevronRight size={16}/></Link></div></article> }

export function BookingApp() {
  const path = usePathname(); const router = useRouter(); const parts = path.split("/").filter(Boolean).slice(1);
  const [bookings, setBookings] = useState<Booking[]>([]); const [ready, setReady] = useState(false); const [query, setQuery] = useState(""); const [draft, setDraft] = useState<{ sessionId?: string; childId?: string }>({}); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [submissionId, setSubmissionId] = useState("");
  useEffect(() => { async function initialise() { if (!isDemoSignedIn()) { router.replace("/login"); return; } try { setBookings(loadBookings()); setDraft(JSON.parse(sessionStorage.getItem("playnest-draft") || "{}")); setSubmissionId(crypto.randomUUID()); } catch (e) { setError(e instanceof Error ? e.message : "We could not open saved demo data."); } finally { setReady(true); } } void initialise(); }, [router]);
  const updateDraft = (next: { sessionId?: string; childId?: string }) => { try { setDraft(next); sessionStorage.setItem("playnest-draft", JSON.stringify(next)); setError(""); } catch { setError("We could not keep this selection in your browser. Please enable browser storage and try again."); } };
  if (!ready) return <Layout path={path}><div className="loading">Preparing your PlayNest demo…</div></Layout>;
  const activityId = parts[1]; const bookingId = parts[1];
  if (!parts.length) { const upcoming = bookings.filter(b => new Date(getSession(b.sessionId)!.start) > new Date())[0]; return <Layout path={path}><section className="app-hero"><div><h1>Make space for their next favourite thing.</h1><p>Explore thoughtful, age-appropriate sessions for your family. This is a fictional demo; no payment is collected.</p><Action href={`${app}/activities`}>Explore activities</Action></div><img src="/images/playnest/7ad1f400a3e4.jpg" alt="Children enjoying a play activity"/></section>{upcoming && <section className="context-panel"><div><span className="tag">Upcoming</span><h2>{getChild(upcoming.childId)?.name} is booked for {getActivity(upcoming.activityId)?.name}</h2><p>{dateTime(getSession(upcoming.sessionId)!.start)}</p></div><Action href={`${app}/bookings/${upcoming.id}`} muted>View booking</Action></section>}<section className="section-head"><div><h2>Find a good fit</h2><p>Every session clearly shows age range, duration, and availability.</p></div><Link href={`${app}/activities`} className="text-link">See all activities <ChevronRight size={16}/></Link></section><div className="activity-grid">{activities.slice(0,3).map(a => <ActivityCard key={a.id} activity={a} bookings={bookings}/>)}</div></Layout>; }
  if (parts[0] === "activities" && parts.length === 1) { const shown = activities.filter(a => a.name.toLowerCase().includes(query.toLowerCase()) || `${a.ages[0]}-${a.ages[1]}`.includes(query)); return <Layout path={path}><header className="page-heading"><h1>Activities</h1><p>Choose a session that fits their age, interest, and your day.</p></header><label className="search"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search activities or age" aria-label="Search activities"/></label><div className="activity-grid">{shown.map(a => <ActivityCard key={a.id} activity={a} bookings={bookings}/>)}</div>{!shown.length && <div className="empty"><Search size={28}/><h2>No activities match that search</h2><button onClick={() => setQuery("")}>Clear search</button></div>}</Layout>; }
  if (parts[0] === "activities" && parts.length === 2) { const activity = getActivity(activityId); if (!activity) return <Missing/>; return <Layout path={path}><Link className="back" href={`${app}/activities`}><ArrowLeft size={17}/> All activities</Link><section className="detail"><img src={activity.image} alt={`${activity.name} activity in progress`}/><div><span className="tag">Ages {activity.ages[0]}–{activity.ages[1]}</span><h1>{activity.name}</h1><p>{activity.description}</p><dl><div><dt>Duration</dt><dd>{activity.minutes} minutes</dd></div><div><dt>Where</dt><dd>{activity.location}</dd></div><div><dt>With</dt><dd>{activity.instructor}</dd></div><div><dt>Demo price</dt><dd>{money(activity.price)}</dd></div></dl><Action href={`${app}/activities/${activity.id}/book`}>Choose a session</Action></div></section></Layout>; }
  if (parts[0] === "activities" && parts[2] === "book") { const activity = getActivity(activityId); if (!activity) return <Missing/>; const session = getSession(draft.sessionId); const child = getChild(draft.childId); const options = sessions.filter(s => s.activityId === activity.id); const complete = Boolean(session && child); return <Layout path={path}><Link className="back" href={`${app}/activities/${activity.id}`}><ArrowLeft size={17}/> {activity.name}</Link><header className="page-heading compact"><h1>Choose a session</h1><p>Then select the child who will attend.</p></header>{error && <p role="alert" className="error">{error}</p>}<div className="booking-layout"><section><h2>Available sessions</h2><div className="choice-list">{options.map(s => { const spots = remaining(s, bookings); const disabled = s.status !== "scheduled" || spots < 1; return <button key={s.id} type="button" aria-pressed={session?.id === s.id} disabled={disabled} className={`choice ${session?.id === s.id ? "selected" : ""}`} onClick={() => updateDraft({ sessionId: s.id, childId: undefined })}><span><b>{dateTime(s.start)}</b><small><MapPin size={14}/>{activity.location}</small></span><em>{disabled ? "Full — choose another time" : `${spots} spots left`}</em></button> })}</div>{session && <><h2 className="choice-heading">Who is attending?</h2><div className="choice-list">{children.map(c => { const okay = eligible(c, activity); return <button key={c.id} type="button" aria-pressed={child?.id === c.id} disabled={!okay} className={`choice child ${child?.id === c.id ? "selected" : ""}`} onClick={() => updateDraft({ ...draft, childId: c.id })}><span className="child-name"><i style={{ background: c.color }}>{c.name.slice(0,1)}</i><b>{c.name}<small>{ageOf(c.dob)} years old</small></b></span><em>{okay ? "Eligible" : `For ages ${activity.ages[0]}–${activity.ages[1]}`}</em></button> })}</div></>}</section><aside className="summary"><span className="tag">Your selection</span><h2>{activity.name}</h2>{session ? <p>{dateTime(session.start)}</p> : <p>Choose an available session to continue.</p>}{child && <p>Attending: <b>{child.name}</b></p>}<button className="action secondary review-action" disabled={!complete} onClick={() => router.push(`${app}/activities/${activity.id}/review`)}>Review booking <ChevronRight size={17}/></button></aside></div></Layout>; }
  if (parts[0] === "activities" && parts[2] === "review") { const activity = getActivity(activityId); const session = getSession(draft.sessionId); const child = getChild(draft.childId); if (!activity || !session || !child) return <Layout path={path}><div className="empty"><XCircle size={28}/><h2>Choose a session and child first</h2><Action href={`${app}/activities/${activityId}/book`}>Return to booking</Action></div></Layout>; const confirm = () => { if (busy || !submissionId) return; setBusy(true); try { const booking = createBooking({ activityId: activity.id, sessionId: session.id, childId: child.id, submissionId }); setBookings(loadBookings()); sessionStorage.removeItem("playnest-draft"); setSubmissionId(crypto.randomUUID()); router.replace(`${app}/bookings/${booking.id}`); } catch (e) { setError(e instanceof Error ? e.message : "We could not save this booking."); setBusy(false); } }; return <Layout path={path}><Link className="back" href={`${app}/activities/${activity.id}/book`}><ArrowLeft size={17}/> Change selection</Link><div className="review"><section><header className="page-heading compact"><h1>Review your booking</h1><p>Confirm the details before saving your demo booking.</p></header><dl className="review-list"><div><dt>Activity</dt><dd>{activity.name}</dd></div><div><dt>When</dt><dd>{dateTime(session.start)}</dd></div><div><dt>Attending</dt><dd>{child.name}, age {ageOf(child.dob)}</dd></div><div><dt>Where</dt><dd>{activity.location} · {activity.instructor}</dd></div><div><dt>Price</dt><dd>{money(activity.price)} <small>Informational only</small></dd></div></dl>{error && <p role="alert" className="error">{error}</p>}<button className="action button-action" disabled={busy} aria-busy={busy} onClick={confirm}>{busy ? "Saving booking…" : "Confirm demo booking"} <CheckCircle2 size={17}/></button></section><aside className="notice"><b>Demo booking</b><p>No payment, email, or real reservation is created. It is stored only in this browser.</p></aside></div></Layout>; }
  if (parts[0] === "bookings" && parts.length === 1) { const upcoming = bookings.filter(b => new Date(getSession(b.sessionId)!.start) > new Date()); const past = bookings.filter(b => new Date(getSession(b.sessionId)!.start) <= new Date()); return <Layout path={path}><header className="page-heading"><h1>My bookings</h1><p>Your saved demo bookings live on this browser.</p></header>{upcoming.length ? <BookingGroup title="Upcoming" bookings={upcoming}/> : <div className="empty"><CalendarDays size={28}/><h2>Nothing booked yet</h2><p>Find an activity, choose a session, and save a demo booking.</p><Action href={`${app}/activities`}>Explore activities</Action></div>}{past.length ? <BookingGroup title="Past" bookings={past}/> : null}</Layout>; }
  if (parts[0] === "bookings" && parts[2] === "pass") { const booking = bookings.find(b => b.id === bookingId); if (!booking) return <Missing/>; const s = getSession(booking.sessionId)!; if (new Date(s.start) <= new Date()) return <Layout path={path}><div className="empty"><QrCode size={28}/><h2>This demo pass has expired</h2><Action href={`${app}/bookings/${booking.id}`}>View booking</Action></div></Layout>; return <Layout path={path}><Link className="back" href={`${app}/bookings/${booking.id}`}><ArrowLeft size={17}/> Booking details</Link><section className="pass"><span className="tag">Demo check-in pass</span><h1>{getChild(booking.childId)?.name}</h1><p>{getActivity(booking.activityId)?.name}</p><div className="qr" aria-label="Decorative demo QR code"><QrCode size={170}/></div><b>{booking.reference}</b><p>{dateTime(s.start)} · {getActivity(booking.activityId)?.location}</p><div className="notice">Demo only — reception validation is not connected.</div></section></Layout>; }
  if (parts[0] === "bookings" && parts.length === 2) { const booking = bookings.find(b => b.id === bookingId); if (!booking) return <Missing/>; const activity = getActivity(booking.activityId)!; const session = getSession(booking.sessionId)!; return <Layout path={path}><Link className="back" href={`${app}/bookings`}><ArrowLeft size={17}/> My bookings</Link><section className="booking-detail"><span className="tag">Confirmed demo booking</span><CheckCircle2 size={38}/><h1>You’re all set</h1><p>Your booking was saved in this browser.</p><dl className="review-list"><div><dt>Reference</dt><dd>{booking.reference}</dd></div><div><dt>Activity</dt><dd>{activity.name}</dd></div><div><dt>Attending</dt><dd>{getChild(booking.childId)?.name}</dd></div><div><dt>When</dt><dd>{dateTime(session.start)}</dd></div></dl>{new Date(session.start) > new Date() && <Action href={`${app}/bookings/${booking.id}/pass`}>Open demo pass</Action>}</section></Layout>; }
  if (parts[0] === "profile") return <Layout path={path}><header className="page-heading"><h1>Family profile</h1><p>Fictional household data used to demonstrate eligibility.</p></header><section className="family"><div className="parent"><span>SR</span><div><b>Sarah Reyes</b><p>Demo parent account</p></div></div>{children.map(c => <div key={c.id} className="family-child"><i style={{ background: c.color }}>{c.name.slice(0,1)}</i><div><b>{c.name}</b><p>{ageOf(c.dob)} years old · Demo profile</p></div></div>)}</section><section className="reset"><h2>Reset this demo</h2><p>This permanently removes saved bookings from this browser. Your fictional family profile stays available.</p><button onClick={() => { if (confirm("Remove all saved demo bookings from this browser?")) { saveBookings([]); setBookings([]); } }}>Reset saved bookings</button></section></Layout>;
  return <Missing/>;
}
function BookingGroup({ title, bookings }: { title: string; bookings: Booking[] }) { return <section className="booking-group"><h2>{title}</h2>{bookings.map(b => <Link key={b.id} href={`${app}/bookings/${b.id}`} className="booking-row"><span><b>{getChild(b.childId)?.name} · {getActivity(b.activityId)?.name}</b><small>{dateTime(getSession(b.sessionId)!.start)} · {b.reference}</small></span><ChevronRight size={19}/></Link>)}</section> }
function Missing() { return <Layout path=""><div className="empty"><XCircle size={28}/><h2>We couldn’t find that page</h2><Action href={app}>Return home</Action></div></Layout> }
